# Generated by Django 3.2.11 on 2022-04-04 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('average_cost', models.IntegerField(default=0)),
                ('product_category', models.CharField(choices=[('TV', 'TV'), ('Tablet', 'Tablet'), ('Phone', 'Phone')], max_length=15)),
                ('release_date', models.DateField(default=datetime.date)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('UK', 'UK'), ('France', 'France'), ('Germany', 'Germany'), ('Spain', 'Spain')], max_length=15)),
                ('user_photo', models.ImageField(upload_to='user_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date)),
            ],
        ),
    ]
