# Generated by Django 3.2.11 on 2022-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
    ]
