# Generated by Django 3.2.11 on 2022-04-07 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopApp', '0008_auto_20220407_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('TV', 'TV'), ('Laptop', 'Laptop'), ('Phone', 'Phone')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebShopApp.review'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('UK', 'UK'), ('France', 'France'), ('Germany', 'Germany'), ('Spain', 'Spain')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
