# Generated by Django 3.2.11 on 2022-04-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopApp', '0012_auto_20220407_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, to='WebShopApp.Review'),
        ),
    ]
